### ISSUE TITLE
Analyzing post descriptions

### ISSUE THREAD

**Issue by Alfusainey** [hyunji-Hong/Dicos-public#1]
@hyunji-Hong Thanks for opensourcing Dicos 👍 

Am trying to understand what Dicos is doing when analyzing post descriptions and while doing so, I encountered an issue while testing the `Analyze_PostDescription` function inside `Post_Analyzer.py`

You can reproduce the issue with the following example:

Let's say I have a post with ID 1 and the post contains three histories `[1429, 1430, 1431]`, where `1429` is the oldest history and `1431` is the latest history. Assume also that each post history contains the following description:

```
1429: This is how I will deal with such input. (See the comment i mentioned previously).
1430: This is how I will deal with such input. (See the comment i mentioned previously).
1431: This is how I will deal with such input. (See the comment i mentioned previously).
       \nEDIT: I have fixed the thing to handle negative results.
       \n I will not suggest you do that.
```
The code that tries to extract the nouns, verbs and modifiers for all descriptions except those in the oldest history is as follows:
```python
for l in splitExcept_oldest.split('\n'):
    l = " "+l
    nouns = patternNoun.findall(l)
    modifiers = patternModifier.findall(l)
    verbs = patternVerb.findall(l)
```
The code above will first process every line in the description in history 1430 and 1431 (since 1429 is the oldest and is excluded).
When processing line `EDIT: I have fixed the thing to handle negative results`, then the three lists becomes: nouns = [], modifiers = [`'negative'`], verbs = [`'fix'`]. 

However, in the final iteration when processing `I will not suggest you do that`, then the results of the previous lists are overridden (nouns = [], modifiers = [], verbs = []).

Is there a reason why the nouns, verbs and modifiers of the currently processed line overrides a previously calculated value? Is there also a reason why you didn't declare the lists outside of the `for loop`? e.g

```python
nouns = []
modifiers = []
verbs = []
for l in splitExcept_oldest.split('\n'):
    l = " "+l
    nouns.extend(patternNoun.findall(l))
    modifiers.extend(patternModifier.findall(l))
    verbs.extend(patternVerb.findall(l))
```

This way, all of the nouns, verbs and modifiers for all histories except oldest are accumulated (and not overridden).

minor bug: I also noticed that `l` could be empty after applying the split function and when `l` is empty, then findall() will return an empty list for verbs, nouns and modifiers.

**Comment by hyunji-Hong** [comment]
Dear @Alfusainey,
Hi, Thank you for your good comments!

You mentioned the issue at `Analyze_PostDescription` in `Post_Analyzer.py`.

Please understand that there were some mistakes in `Analyze_PostDescription` process due to code refactoring. 😅

To explain the exact operation,
Dicos checks whether all lines in the post description section contain security-related keyword pairs.
Also, **Dicos only checks the oldest and the latest version of the post descriptions**, not considering all versions.
Therefore, I will fix it to check only the oldest version and the latest version.

Hope this helps! :)

**Comment by Alfusainey** [comment]
> Also, Dicos only checks the oldest and the latest version of the post descriptions, not considering all versions.
> Therefore, I will fix it to check only the oldest version and the latest version.

This helps, thanks a lot! Then the idea is similar to what you did when extracting code snippets from version histories.
 Bear with me, i may open a few more issues while trying to understand the code (at least until the paper becomes available 😄 )
