### ISSUE TITLE
detecting API changes

### ISSUE THREAD

**Issue by Alfusainey** [hyunji-Hong/Dicos-public#2]
Hi @hyunji-Hong 

When detecting API changes in C code snippets, you check if the diff line starts with a `-` on [line 160](https://github.com/hyunji-Hong/Dicos-public/blob/a89e35ca26ae07eae93bbe98c0434ca2986fb3de/src/Post_Analyzer.py#L160).

Can you please explain what is the reasoning behind checking for apis changes only in code deletions (excluding additions)? Also, in the java analysis, you're detecting API changes for all diff operations (deletions/additions). Is there a reason why it is differrent for Java code?

**Comment by hyunji-Hong** [comment]
Hi @Alfusainey 
Thank you for a good question, we mentioned it also in our paper.

We defined that deleting or changing the security-sensitive API  is a security fix. (e.g., removing the strcpy function)
So, if deleted code line contains security-sensitive APIs, Dicos will detect it. 

For Java, it seems that we made a mistake during code refactoring.
(we will fix it soon..!)

Thanks.
Best regards,

**Comment by Alfusainey** [comment]
Hi @hyunji-Hong 

ok I see, thank you! I didn't know that your paper was available. I really enjoyed reading it 👍 

When you have time you can (optionally) update the project README with a link to the paper (and also how it can be cited when dicos is used by others)

i will close this issue as resolved, thanks!
