### ISSUE TITLE
Detecting CF changes using Joern

### ISSUE THREAD

**Issue by Alfusainey** [hyunji-Hong/Dicos-public#3]
Hi @hyunji-Hong

In the paper you mentioned that for Dicos to detect `F3`, it looks for changes in control-flows. In listing 6, you gave an example snippet containing changes to if-statements. Does `F3` means changes to **if-statements only** or changes to **any kind of control-flows** (e.g for-loops, while-loops and do-while loops)?

Currently in [line 83](https://github.com/hyunji-Hong/Dicos-public/blob/a89e35ca26ae07eae93bbe98c0434ca2986fb3de/src/Post_Analyzer_usingJoern.py#L83), the query you used detects all kinds of control structures (including while and for-loops). I tested with the following:

```C
joern> val cCode = """static char *binrep (unsigned int x, char *buff, int sz) {
    if (x == 0) {
        strcpy (buff, "0");
        return buff;
    }
    buff += sz;
    *buff-- = '\0';
    while (x != 0) {
        *buff-- = ((x & 1) == 1) ? '1' : '0';
        x >>= 1;
    }
    return buff+1;
}
""".stripMargin

joern> importCode.c.fromString(cCode)
```

And the query: `cpg.method.name("binrep").controlStructure.code.toJsonPretty`, Joern returns:

```scala
res6: String = """[
  "if (x == 0)",
  "while (x != 0)"
]"""
```

So Joern returns both the if and while statements since they're both considered control structures.

Is this a refactoring bug or this output reflects what `F3` means in the paper?

Edit: I also tested the `controlStructure` query with a Java code snippet and Joern reported the `try` block as a control-structure. E.g

```Java
joern> val javaCode = """public class WebClientDevWrapper {
    public static HttpClient wrapHttpClient(HttpClient base) {
    	if (base == null) {
    		return null
    	}
        try {
            SSLContext ctx = SSLContext.getInstance("TLS");
            X509TrustManager tm = new X509TrustManager() {

                public void checkClientTrusted(X509Certificate[] xcs,
                        String string) throws CertificateException {
                }

                public void checkServerTrusted(X509Certificate[] xcs,
                        String string) throws CertificateException {
                }

                public X509Certificate[] getAcceptedIssuers() {
                    return new X509Certificate[]{};
                }
            };
            ctx.init(null, new TrustManager[] { tm }, null);
            SSLSocketFactory ssf = new SSLSocketFactory(ctx);
                ssf.setHostnameVerifier(SSLSocketFactory.ALLOW_ALL_HOSTNAME_VERIFIER);
            ClientConnectionManager ccm = base.getConnectionManager();
            SchemeRegistry sr = ccm.getSchemeRegistry();
            sr.register(new Scheme("https", ssf, 443));
            DefaultHttpClient client= new DefaultHttpClient(ccm, base.getParams());
            return client;
        } catch (Exception ex) {
            ex.printStackTrace();
            return null;
        }
    }

}""".stripMargin

joern> importCode.java.fromString(javaCode)
```

Then the query `cpg.method.name("wrapHttpClient").controlStructure.code.toJsonPretty` returns:

```scala
res18: String = """[
  "if (base == null)",
  "try"
]"""
```

However, if I change the query to retrieve only if-statements using `cpg.method.name("...").ifBlock.code.toJsonPretty`, then I only get the if-statements

**Comment by hyunji-Hong** [comment]
Hi @Alfusainey 
Thank you for your question.

Dicos considers both (1) a change in the direction of control flows (e.g., adding if statement) and (2) a change
in the conditions of each conditional statement even though the direction of control flows remains unchanged (e.g., changing a condition in an if statement).

We did not consider the case such as for-loops and while-loops.

Since StackOverflow has a lot of code snippets that are not function units, our main implementation is [Post_Analyzer.py](https://github.com/hyunji-Hong/Dicos-public/blob/main/src/Post_Analyzer.py).

Thanks,
